### ISSUE TITLE
标签不应该是真实噪声嘛？

### ISSUE THREAD

**Issue by chaoyueziji** [husqin/DnCNN-keras#1]
在代码中的train_datagen，返回的是ge_batch_x, ge_batch_y，ge_batch_y不是干净图片嘛？

**Comment by chaoyueziji** [comment]
还有就是当训练得到的图片不应该是要转成uint8在进行计算psnr嘛？

**Comment by husqin** [comment]
你好。我在模型里面把输入减去了输出，所以标签是干净图片，在预测的时候输出的直接就是降噪后的图片。计算psnr的时候我用的是skimage的compare_psnr函数，输入图片如果是float，它会自动把psnr公式里的MAX设成1，这样应该也是可以的。

**Comment by chaoyueziji** [comment]
谢谢您回复，如果转为整型后计算结果会有降低，大约降低0.0x左右
